if(!isServer) exitwith {};

clearWeaponCargoGlobal _this;
clearMagazineCargoGlobal _this;
clearItemCargoGlobal _this;
clearBackpackCargoGlobal _this;

_this addWeaponCargoGlobal ["rhs_weap_m16a4", 20];
_this addWeaponCargoGlobal ["rhs_weap_m16a4_carryhandle", 20];
_this addWeaponCargoGlobal ["rhs_weap_m16a4_carryhandle_grip", 20];
_this addWeaponCargoGlobal ["rhs_weap_m16a4_carryhandle_grip_pmag", 20];
_this addWeaponCargoGlobal ["rhs_weap_m16a4_carryhandle_M203", 20];
_this addWeaponCargoGlobal ["rhs_weap_m16a4_carryhandle_pmag", 20];
_this addWeaponCargoGlobal ["rhs_weap_m16a4_grip", 20];
_this addWeaponCargoGlobal ["rhs_weap_m240B", 20];
_this addWeaponCargoGlobal ["rhs_weap_m249_pip_L", 20];
_this addWeaponCargoGlobal ["rhs_weap_m249_pip_L_para", 20];
_this addWeaponCargoGlobal ["rhs_weap_m249_pip_L_vfg", 20];
_this addWeaponCargoGlobal ["rhs_weap_m249_pip_S", 20];
_this addWeaponCargoGlobal ["rhs_weap_m249_pip_S_para", 20];
_this addWeaponCargoGlobal ["rhs_weap_m249_pip_S_vfg", 20];
_this addWeaponCargoGlobal ["rhs_weap_m27iar", 20];
_this addWeaponCargoGlobal ["rhs_weap_m4a1_carryhandle", 20];
_this addWeaponCargoGlobal ["rhs_weap_m4a1_carryhandle_grip2", 20];
_this addWeaponCargoGlobal ["rhs_weap_m4a1_carryhandle_pmag", 20];
_this addWeaponCargoGlobal ["rhs_weap_m4a1_carryhandle_grip", 20];
_this addWeaponCargoGlobal ["rhs_weap_m4a1_carryhandle_m203", 20];
_this addWeaponCargoGlobal ["rhs_weap_m4a1_carryhandle_m203S", 20];
_this addWeaponCargoGlobal ["rhs_weap_m4a1", 20];
_this addWeaponCargoGlobal ["rhs_weap_m4a1_grip2", 20];
_this addWeaponCargoGlobal ["rhs_weap_m4a1_grip", 20];
_this addWeaponCargoGlobal ["rhs_weap_m4a1_m203", 20];
_this addWeaponCargoGlobal ["rhs_weap_m4a1_m203s", 20];
_this addWeaponCargoGlobal ["rhs_weap_m4a1_m320", 20];
_this addWeaponCargoGlobal ["rhs_weap_M590_8RD", 20];
_this addWeaponCargoGlobal ["rhs_weap_M590_5RD", 20];
_this addWeaponCargoGlobal ["rhs_weap_m4_grip2", 20];
_this addWeaponCargoGlobal ["rhs_weap_m4_carryhandle", 20];
_this addWeaponCargoGlobal ["rhs_weap_m4_carryhandle_pmag", 20];
_this addWeaponCargoGlobal ["rhs_weap_m4_grip", 20];
_this addWeaponCargoGlobal ["rhs_weap_m4_m203", 20];
_this addWeaponCargoGlobal ["rhs_weap_m4_m203S", 20];
_this addWeaponCargoGlobal ["rhs_weap_m4_m320", 20];
_this addWeaponCargoGlobal ["hlc_smg_mp5a4", 20];
_this addWeaponCargoGlobal ["hlc_smg_MP5N", 20];
_this addWeaponCargoGlobal ["rhs_weap_sr25_ec", 20];
_this addWeaponCargoGlobal ["rhs_weap_sr25", 20];
_this addWeaponCargoGlobal ["rhs_weap_m14ebrri", 20];
_this addWeaponCargoGlobal ["rhs_weap_XM2010", 20];
_this addWeaponCargoGlobal ["RH_Mk11", 20];
_this addWeaponCargoGlobal ["RH_Mk12mod1", 20];
_this addWeaponCargoGlobal ["RH_m110", 20];
_this addWeaponCargoGlobal ["RH_m9", 20];
_this addWeaponCargoGlobal ["RH_m1911", 20];
