// A2BM W 110
// DO NOT EDIT THIS FILE

waitUntil {!(isNull player)};
waitUntil {player==player};
switch (side player) do
{
case WEST:
{
MAG_tskObj0=player createSimpleTask ["INFORMACIÓN"];
MAG_tskObj0 setSimpleTaskDescription ["11OCT15 1700<br/>SITUACIÓN<br/>En esta parte de Iraq, el ejército iraquí se esta viendo envuelto en duros enfrentamientos contra miembros del ISIS. Un grupo de operaciones especiales de los EEUU se encuentra en esta región para entrenar a las fuerzas de especiales iraquíes en su lucha contra los terroristas. <br/><br/>BIREFING<br/>Se están produciendo duros enfrentamientos entre los terroristas y el ejército iraquí. En varios puntos hombres uniformados como tropas regulares iraquíes está atacando por sorpresa a las fuerzas regulares, sembrando el caos y la confusión.<br/>En este momento el gobernador de la zona se disponía a ser evacuado a un aeropuerto, para desde allí ser puesto a salvo bajo protección de los EEUU. Pero el convoy con el gobernador no ha podido salir y se ha quedado atrapado en I´timad.<br/>Se ha solicitado a las fuerzas especiales de los EEUU ayuda para sacar de la zona al gobernador.<br/>El objetivo es llegar a I´Timad y sacar al gobernador. Tendrán que llevarlo a una zona segura y desde allí solicitar un helicóptero (ALIVE)  para la extracción. Una vez el gobernador a salvo el objetivo principal de la misión se dará por cumplido.<br/>Luego pueden volver a base o ayudar al ejército iraquí en la zona.<br/>","INFORMACIÓN","INFORMACIÓN"];
};
case EAST:
{
};
case RESISTANCE:
{
};
case CIVILIAN:
{
};
};
